--[[

File:  amk_utils .script
Created:  23.05.2008
Copyright:  © 2008 AMK team
Author:  Refresh
Version:  1.1.0.0

--]]


--* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-- *			                         Callback 					                 *
--* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

--Callback на старт игры
function start_game()
end

--Callback на апдейт монстров (работает постоянно)
function monster_update(delta)
end

--Callback на смерть монстров
function monster_death(victim, who)
end

--Callback на хит монстра
function monster_hit(obj, amount, local_direction, who, bone_index)
end

--Callback юзания обьекта
function physics_use(obj, who)
end

--Callback на хит обьекта
function physics_hit(obj, amount, local_direction, who, bone_index)
end

--Callback на "смерть" обьекта
function physics_death(victim, who)
end

--Callback на инфопоршен
function actor_info(npc, info_id)
end

--Callback на заход на уровень
function actor_level_border_enter(npc, info_id)
end

--Callback на выход с уровня
function actor_level_border_exit(npc, info_id)
end

--Callback на полученияе артикла
function actor_article(npc, group, name)
end

--Callback на взятия предмета в инвентарь гг из ящика
function actor_item_from_box(box, item)
	if item ~= nil then
		restriction_stock.restriction_of_stock(item)
	end
end

--Callback на взятие предмета в инвентарь гг
function actor_item_take(obj)
	if obj ~= nil then
		restriction_stock.restriction_of_stock(obj)
	end
end

--Callback на потерю предмета из инвенаря гг
function actor_item_drop(obj)
end

--Callback на получение тасков
function actor_task(_task, _objective, _state)
end

--Callback на апдейт актора  (работает постоянно)
function actor_update(delta)
end


--* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-- *			                         Inventory					       *
--* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

--Проверка на количество предметов в инвентаре гг
function inventory_search(_item, n)
	local  actor = db.actor
	local  count = 0
	actor:iterate_inventory(function (dummy, item) if item:section()== _item then count=count+1 end end, nil)
	if count >= n then
		return true
	else
		return false
	end
end

--Проверка на предмет в инвентаре гг
function have_a_item(_item)
    local actor = db.actor
    if actor ~= nil and actor:object(_item) ~= nil then
		return true
	else
		return false
	end
end

--Проверка на предмет в инветаре и выдачу инфопоршена
function have_a_item_info(_item, _info)
    local actor = db.actor
    if actor ~= nil and actor:object(_item) ~= nil and actor:dont_has_info(_info) then
		actor:give_info_portion(_info)
	end
end

--Проверка инфопоршенов
function have_a_info(info_has, not_info_has)
	local actor = db.actor
	if has_alife_info(info_has) and not has_alife_info(not_info_has) then
		return true
	else
		return false
	end
end

--Проверка денег у гг
function actor_has_money(_money)
	local actor = db.actor
	if actor:money() >= _money then
		return true
	else
		return false
	end
end

--* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-- *			                         Transfers					       *
--* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

--Трансфер денег между гг и нпс
function actor_give_money(_npc, _actor, _money, type)
	local actor, npc
	if db.actor and db.actor:id() == npc:id() then
		actor = _npc
		npc = _actor
	else
		actor = _actor
		npc = _npc
	end
	
	if type == "out" then
		dialogs.relocate_money(npc, _money, "out")
	elseif type == "in" then 
		dialogs.relocate_money(npc, _money, "in")
	end
end

--Трансфер предмета между гг и нпс
function actor_give_item(_npc, _actor, _item, _type)
	local actor, npc
	if db.actor and db.actor:id() == npc:id() then
		actor = _npc
		npc = _actor
	else
		actor = _actor
		npc = _npc
	end
	
	if _type == "out" then
		dialogs.relocate_item_section(npc, _item, "out")
	elseif _type == "in" then 
		dialogs.relocate_item_section(npc, _item, "in")
	end
end

--Трансфер предметов между гг и нпс
function relocate_n_items_section(_victim, _section, _type, _count)
    if db.actor and _victim then
		if _type == "in" then
			for i=1,n do
                alife():create(_section,     
				db.actor:position(),
                db.actor:level_vertex_id(),     
                db.actor:game_vertex_id(),
                db.actor:id())
			end
		elseif _type == "out" then
			db.actor:iterate_inventory(function (dummy,item) if item:section() == _section and _count > 0 then 
			db.actor:transfer_item(item, _victim) _count = _count - 1 end end, nil)
		end
		news_manager.relocate_item(db.actor, _type, _section)
    end
end















