function spawn_duty_squad()

    if db.actor == nil then
        return
    end

    if db.actor:has_info("pravo_pri_duty_spawned") then
        return
    end


    -- ========================================================
    -- КОМАНДИР
    -- ========================================================

    local leader = alife():create(
        "pravo_pri_duty_leader_spawn",
        vector():set(
            102.95188903809,
            -0.92949116230011,
            -26.490100860596
        ),
        213633,
        2234
    )


    -- ========================================================
    -- БОЕЦ 1
    -- ========================================================

    local duty1 = alife():create(
        "pravo_pri_duty_1_spawn",
        vector():set(
            103.26148223877,
            -0.94035828113556,
            -30.219137191772
        ),
        214322,
        2234
    )


    -- ========================================================
    -- БОЕЦ 2
    -- ========================================================

    local duty2 = alife():create(
        "pravo_pri_duty_2_spawn",
        vector():set(
            94.766174316406,
            -2.3414041996002,
            -32.325805664063
        ),
        205430,
        2144
    )


    -- ========================================================
    -- БОЕЦ 3
    -- ========================================================

    local duty3 = alife():create(
        "pravo_pri_duty_3_spawn",
        vector():set(
            94.29621887207,
            -2.2847623825073,
            -22.432395935059
        ),
        205444,
        2144
    )


    if leader ~= nil
    and duty1 ~= nil
    and duty2 ~= nil
    and duty3 ~= nil then

        db.actor:give_info_portion(
            "pravo_pri_duty_spawned"
        )
    end
end



function check_intro_finished()

    if db.actor == nil then
        return
    end

    if db.actor:has_info("pravo_pri_unknown_talked")
    and db.actor:has_info("pravo_pri_alexander_talked")
    and not db.actor:has_info("pravo_pri_intro_done") then

        db.actor:give_info_portion(
            "pravo_pri_intro_done"
        )

        spawn_duty_squad()
    end
end



function unknown_finished(first_speaker, second_speaker)

    if db.actor == nil then
        return
    end

    if not db.actor:has_info("pravo_pri_unknown_talked") then

        db.actor:give_info_portion(
            "pravo_pri_unknown_talked"
        )
    end

    check_intro_finished()
end



function alexander_finished(first_speaker, second_speaker)

    if db.actor == nil then
        return
    end

    if not db.actor:has_info("pravo_pri_alexander_talked") then

        db.actor:give_info_portion(
            "pravo_pri_alexander_talked"
        )
    end

    check_intro_finished()
end

function wounded_freedom_give_weapon(first_speaker, second_speaker)

    if db.actor == nil then
        return
    end

    if db.actor:has_info("pravo_pri_wounded_freedom_weapon_given") then
        return
    end

    local actor = db.actor

    alife():create(
        "wpn_walther",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    alife():create(
        "ammo_9x19_fmj",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

      alife():create(
        "wpn_knife",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    alife():create(
        "ammo_9x19_fmj",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    actor:give_info_portion(
        "pravo_pri_wounded_freedom_weapon_given"
    )
end

function freedom_leader_give_vodka(first_speaker, second_speaker)

    if db.actor == nil then
        return
    end

    if db.actor:has_info("pravo_pri_freedom_vodka_given") then
        return
    end

    local actor = db.actor

    alife():create(
        "vodka",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    actor:give_info_portion("pravo_pri_freedom_vodka_given")
end

function freedom_leader_give_dosimeter(first_speaker, second_speaker)

    if db.actor == nil then
        return
    end

    if db.actor:has_info("pravo_rad_dosimeter_given") then
        return
    end

    local actor = db.actor

    if actor:object("detector_simple") == nil then
        alife():create(
            "detector_simple",
            actor:position(),
            actor:level_vertex_id(),
            actor:game_vertex_id(),
            actor:id()
        )
    end

    actor:give_info_portion("pravo_rad_dosimeter_given")
end

function freedom_leader_give_dog_reward(first_speaker, second_speaker)

    if db.actor == nil then
        return
    end

    if db.actor:has_info("pravo_rad_dogs_reward_given") then
        return
    end

    local actor = db.actor

    alife():create(
        "wpn_lr300",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    alife():create(
        "ammo_5.56x45_ss190",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    alife():create(
        "ammo_5.56x45_ss190",
        actor:position(),
        actor:level_vertex_id(),
        actor:game_vertex_id(),
        actor:id()
    )

    actor:give_info_portion("pravo_rad_dogs_reward_given")
end

function actor_has_rad_herb(first_parameter, second_parameter)

    if db.actor == nil then
        return false
    end

    return db.actor:object("pravo_rad_herb") ~= nil
end

function freedom_leader_take_rad_herb(first_speaker, second_speaker)

    if db.actor == nil or second_speaker == nil then
        return
    end

    if db.actor:object("pravo_rad_herb") == nil then
        return
    end

    dialogs.relocate_item_section(
        second_speaker,
        "pravo_rad_herb",
        "out"
    )
end
