--[[

File:  restriction_stock .script
Created:  22.05.2008
Copyright:  © 2008 AMK team
Author:  Refresh
Version:  1.2.0.0 

--]]


function restriction_of_stock(_obj)

	local  actor = db.actor
	local 	_table      = {
	
			_medkit     = { "medkit", "medkit_scientic", "medkit_army" },
			_item       = { "energy_drink","conserva","vodka","bread","kolbasa" },
			_weapons_C1 = { "wpn_abakan","wpn_ak74","wpn_g36","wpn_ak74u","wpn_l85","wpn_groza","wpn_lr300","wpn_val","wpn_fn2000",
							"wpn_spas12","wpn_wincheaster1300","wpn_mp5","wpn_sig220","wpn_ak74_m1","wpn_abakan_m1","wpn_ak74u_m1",
							"wpn_mp5_m1","wpn_groza_m1","wpn_spas12_m1","wpn_winchester_m1","wpn_l85_m1","wpn_lr300_m1","wpn_sig_m1",
							"wpn_val_m1","wpn_mp5_m2","wpn_abakan_m2","wpn_l85_m2","wpn_sig_m2","wpn_bm16" },					 
			_weapons_C2 = { "wpn_desert_eagle","wpn_fort","wpn_hpsa","wpn_walther","wpn_usp","wpn_pb","wpn_beretta","wpn_colt1911",
							"wpn_pm","wpn_eagle_m1","wpn_colt_m1","wpn_walther_m1" },			 
			_weapons_C3 = { "wpn_svu","wpn_svd","wpn_vintorez","wpn_toz34","wpn_gauss","wpn_rg-6","wpn_rpg7","wpn_svd_m1","wpn_rg6_m1"},
			_artefacts  = { "af_medusa","af_cristall_flower","af_night_star","af_vyvert","af_gravi","af_gold_fish",
							"af_blood","af_mincer_meat","af_soul","af_electra_sparkler","af_electra_flash","af_electra_moonlight",
							"af_rusty_thorn","af_rusty_kristall","af_rusty_sea-urchin","af_ameba_slime","af_ameba_slug","af_ameba_mica",
							"af_drops","af_fireball","af_cristall","af_dummy_glassbeads","af_dummy_pellicle","af_dummy_battery","af_dummy_dummy",
							"af_dummy_spring","af_fuzz_kolobok","af_buliz","af_spirit_1","af_spirit_2","af_spirit_3","af_spirit_4","af_cry_1",
							"af_cry_2","af_cry_3","af_babka_1","af_babka_2","af_babka_3","af_pudd_1","af_pudd_2","af_pudd_3","af_pudd_4",
							"af_dik_1","af_dik_2","af_dik_3","af_dik_4","af_kol_1","af_kol_2","af_kol_3","af_kol_4","af_armor_1","af_armor_2",
							"af_armor_3","af_armor_4","af_simbion" },				 
			_outfits    = { "novice_outfit","bandit_outfit","killer_outfit","monolit_outfit","soldier_outfit","specops_outfit","military_outfit",
							"stalker_outfit","scientific_outfit","exo_outfit","svoboda_light_outfit","svoboda_heavy_outfit","dolg_outfit","dolg_scientific_outfit",
							"ecolog_outfit","protection_outfit","militaryspec_outfit","svoboda_gaz_outfit_m1","dolg_gaz_outfit_m1","neytral_gaz_outfit_m1",
							"neytral_novice_gaz_outfit_m1","neytral_novice_outfit_m1","svoboda_yellow_exo_outfit_m1","killer_gaz_outfit_m1",
							"svoboda_heavy_gaz_outfit_m1","bandit_veteran_outfit_m1","bandit_gaz_outfit_m1","monolit_gaz_outfit_m1","neytral_exo_gaz_outfit_m1",
							"outfit_novice_m1","outfit_bandit_m1","outfit_dolg_m1","outfit_killer_m1","outfit_specnaz_m1","outfit_stalker_m1","outfit_stalker_m2",
							"outfit_svoboda_m1","outfit_exo_m1" }
			}
						 
	for kk,vv in pairs(_table) do
		local count = 0
		for k,v in pairs(vv) do
			local _item = v 
			actor:iterate_inventory(function (dummy, item) if item:section()== _item then count=count+1 end end, nil)
			if  kk == "_medkit" and count>25 then
				amk.send_tip("Аптечек и так хватит на роту солдат!",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			elseif  kk == "_item" and count>20 then
				amk.send_tip("Вот уж этого пока вполне хвататет.",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			elseif kk == "_weapons_C1" and count>2 then
				amk.send_tip("Совершенно некуда вешать.",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			elseif kk == "_weapons_C2" and count>4 then
				amk.send_tip("Пистолетов и так предостаточно.",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			elseif kk == "_weapons_C3" and count>1 then
				amk.send_tip("Это оружие слишком громоздкое.",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			elseif kk == "_artefacts" and count>20 then
				amk.send_tip("Артефакты уже некуда класть.",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			elseif kk == "_outfits" and count>2 then
				amk.send_tip("Гардероб забит!",nil,nil,5)
				amk.drop_item(actor,_obj)
				break
			end		
		end
	end
end